Initial Russian Translation
InvisibleManVPN/InvisibleMan-XRayClient pull request #129
Opened 2024-09-14 13:57 UTC by smalyu

Initial version of the translation to Russian. The current translation is already decent, but I will review it more thoroughly later and may introduce further improvements.

2024-09-18 08:28 UTC, InvisibleManVPN commented
Hey @smalyu!
Really thanks for your contribution. I will check it and merge it. Also, if there is anything that needs to be changed, I will let you know.

2024-09-18 09:19 UTC, torikki-tou requested changes
Some small comments in russian because it is very language specific and irrelevant for non-russian speaking people

2024-09-18 09:19 UTC, torikki-tou commented on InvisibleMan-XRay/Assets/Localization/ru-RU.xaml
> +    <system:String x:Key="Lang.Window.About.ContactUs">Также вы можете связаться с нами, отправив электронное письмо. Мы постараемся ответить вам как можно скорее!</system:String>
лучше `связаться с нами по email.`, так никто не говорит

2024-09-18 09:19 UTC, torikki-tou commented on InvisibleMan-XRay/Assets/Localization/ru-RU.xaml
> +    <system:String x:Key="Lang.Window.Policy.DataSecurityDescription">Мы серьезно относимся к безопасности ваших данных. Мы внедрили современные меры безопасности для защиты аналитических данных, кот
`Мы внедрили современные меры для` иначе повтор слова безопасность

2024-09-18 09:19 UTC, torikki-tou commented on InvisibleMan-XRay/Assets/Localization/ru-RU.xaml
> +    <system:String x:Key="Lang.Window.Server.Import.Remarks">Название подписки</system:String>
разве здесь не должно быть `примечания`?

2024-09-18 09:19 UTC, torikki-tou commented on InvisibleMan-XRay/Assets/Localization/ru-RU.xaml
> +    <system:String x:Key="Lang.Window.Settings.Tab.Log">Лог</system:String>
Возможно имеет смысл использовать слово `журнал`, но я не уверен

2024-09-18 09:19 UTC, torikki-tou commented on InvisibleMan-XRay/Assets/Localization/ru-RU.xaml
> +    <system:String x:Key="Lang.Window.Settings.Log.Level">Уровень лога</system:String>
также возможно `уровень журнала` или вообще переформулировать, чтобы был понятен смысл

2024-09-18 09:19 UTC, torikki-tou commented on InvisibleMan-XRay/Assets/Localization/ru-RU.xaml
> +    <system:String x:Key="Lang.Window.Settings.Log.Path">Путь лога</system:String>
`Путь до файла` возможно тоже `журнала`

2024-09-18 09:19 UTC, torikki-tou commented on InvisibleMan-XRay/Assets/Localization/ru-RU.xaml
> +    <system:String x:Key="Lang.Message.ThereIsNoConfiguration">Конфигурации отсутствуют</system:String>
`Отсутствуют конфигурации`, чтобы надписи также различались, как в английской версии

2024-09-18 09:19 UTC, torikki-tou commented on InvisibleMan-XRay/Assets/Localization/ru-RU.xaml
> +    <system:String x:Key="Lang.Message.CantConnectToTunnelService">Приложение не может подключиться к туннельному сервису.</system:String>
`к сервису-туннелю`

2024-09-18 09:19 UTC, torikki-tou commented on InvisibleMan-XRay/Assets/Localization/ru-RU.xaml
> +    <system:String x:Key="Lang.Message.CantProxySystem">Приложение не может проксировать систему.</system:String>
`проксировать системные запросы`

2024-09-18 09:19 UTC, torikki-tou commented on InvisibleMan-XRay/Assets/Localization/ru-RU.xaml
> +    <system:String x:Key="Lang.Message.CantTunnelSystem">Приложение не может туннелировать систему.</system:String>
`туннелировать системные запросы`

2024-09-18 09:19 UTC, torikki-tou commented on InvisibleMan-XRay/Assets/Localization/ru-RU.xaml
> +    <system:String x:Key="Lang.Message.NoSubscriptionRemarksEntered" xml:space="preserve">Название подписки не введено.&#10;Пожалуйста, заполните это поле.</system:String>
Снова название подписки, хотя в английской версии `Remarks`, может это у них ошибка?

@InvisibleManVPN does `SubscriptionRemarks` mean the name of subscription?

2024-09-18 09:19 UTC, torikki-tou commented on InvisibleMan-XRay/Assets/Localization/ru-RU.xaml
> +    <system:String x:Key="Lang.Message.NoLogFile" xml:space="preserve">Файл лога для этой конфигурации отсутствует.&#10;Вы можете управлять логами через меню настроек.</system:String>
возможно снова `журнал`

2024-09-18 09:24 UTC, smalyu commented on InvisibleMan-XRay/Assets/Localization/ru-RU.xaml
> +    <system:String x:Key="Lang.Window.About.VisitWebsite">Пожалуйста, посетите сайт, чтобы загрузить последнюю версию или получить помощь и информацию.</system:String>
согласен, поправлю

2024-09-18 09:24 UTC, InvisibleManVPN commented on InvisibleMan-XRay/Assets/Localization/ru-RU.xaml
> +    <system:String x:Key="Lang.Message.NoSubscriptionRemarksEntered" xml:space="preserve">Название подписки не введено.&#10;Пожалуйста, заполните это поле.</system:String>
Hey @torikki-tou.
Thanks for reviewing. Yep, exactly.

2024-09-18 09:24 UTC, smalyu commented on InvisibleMan-XRay/Assets/Localization/ru-RU.xaml
> +    <system:String x:Key="Lang.Window.About.ContactUs">Также вы можете связаться с нами, отправив электронное письмо. Мы постараемся ответить вам как можно скорее!</system:String>
тоже согласен, исправлю

2024-09-18 09:29 UTC, smalyu commented on InvisibleMan-XRay/Assets/Localization/ru-RU.xaml
> +    <system:String x:Key="Lang.Window.Server.Import.Remarks">Название подписки</system:String>
Я думал об этом. Дословный перевод Remarks — это Примечания, да. Но, по логике, мне кажется, что для русскоязычного пользователя это не совсем понятно, что подразумевается под "Примечания". И что это больше похоже на "Название подписки". Что думаешь? Я не уверен ни в своём варианте, ни в "Примечания".

2024-09-18 09:29 UTC, smalyu commented on InvisibleMan-XRay/Assets/Localization/ru-RU.xaml
> +    <system:String x:Key="Lang.Window.Policy.DataSecurityDescription">Мы серьезно относимся к безопасности ваших данных. Мы внедрили современные меры безопасности для защиты аналитических данных, кот
ок

2024-09-18 09:30 UTC, InvisibleManVPN commented on InvisibleMan-XRay/Assets/Localization/ru-RU.xaml
> +    <system:String x:Key="Lang.Window.Settings.Title">НАСТРОЙКИ</system:String>
@smalyu Also for the Settings window, can you please add the subtitle to make it the same as other windows? I mean we want to have the same style for all windows.

![image](https://github.com/user-attachments/assets/e71ceb51-c68d-4cd3-a781-b64f98d0a16d)

2024-09-18 09:31 UTC, smalyu commented on InvisibleMan-XRay/Assets/Localization/ru-RU.xaml
> +    <system:String x:Key="Lang.Window.Settings.Tab.Log">Лог</system:String>
Здесь я тоже думал, но, в целом, слово лог и логи уже стали частью русского языка, как мне кажется.

2024-09-18 09:32 UTC, smalyu commented on InvisibleMan-XRay/Assets/Localization/ru-RU.xaml
> +    <system:String x:Key="Lang.Message.CantConnectToTunnelService">Приложение не может подключиться к туннельному сервису.</system:String>
ок

2024-09-18 09:32 UTC, smalyu commented on InvisibleMan-XRay/Assets/Localization/ru-RU.xaml
> +    <system:String x:Key="Lang.Message.CantProxySystem">Приложение не может проксировать систему.</system:String>
ок

2024-09-18 09:33 UTC, smalyu commented on InvisibleMan-XRay/Assets/Localization/ru-RU.xaml
> +    <system:String x:Key="Lang.Message.CantTunnelSystem">Приложение не может туннелировать систему.</system:String>
ок

2024-09-18 09:44 UTC, smalyu commented on InvisibleMan-XRay/Assets/Localization/ru-RU.xaml
> +    <system:String x:Key="Lang.Message.ThereIsNoConfiguration">Конфигурации отсутствуют</system:String>
Не совсем понял, почему это плохо, если они одинаковые? Они ведь отображаются на разных экранах

2024-09-18 09:49 UTC, smalyu commented on InvisibleMan-XRay/Assets/Localization/ru-RU.xaml
> +    <system:String x:Key="Lang.Window.Settings.Title">НАСТРОЙКИ</system:String>
@torikki-tou, как думаешь, как лучше подписать, чтобы не получилось 'масло масляное'? Настроить параметры? Установить параметры? В оригинале - Customize your settings

2024-09-18 09:58 UTC, smalyu commented on InvisibleMan-XRay/Assets/Localization/ru-RU.xaml
> +    <system:String x:Key="Lang.Message.NoSubscriptionRemarksEntered" xml:space="preserve">Название подписки не введено.&#10;Пожалуйста, заполните это поле.</system:String>
@torikki-tou что в таком случае думаешь? Оставляем как есть? Или есть идеи как можно улучшить?

2024-09-18 10:01 UTC, smalyu commented on InvisibleMan-XRay/Assets/Localization/ru-RU.xaml
> +    <system:String x:Key="Lang.Window.Settings.Log.Level">Уровень лога</system:String>
Я хотел - Уровень логирования. Но не помещается в поле(

2024-09-18 10:09 UTC, smalyu commented on InvisibleMan-XRay/Assets/Localization/ru-RU.xaml
> +    <system:String x:Key="Lang.Window.Settings.Log.Path">Путь лога</system:String>
Мне просто кажется, что если человек не знает что такое лог, то ему этот раздел и не нужен. А слово журнал более общее и может ввести в заблуждение. Как тебе вот такой вариант этого раздела?
<img width="336" alt="image" src="https://github.com/user-attachments/assets/2386fea5-b588-48f2-b7e8-c8b0857d3274">

2024-09-18 10:14 UTC, smalyu commented on InvisibleMan-XRay/Assets/Localization/ru-RU.xaml
> +    <system:String x:Key="Lang.Window.Settings.Title">НАСТРОЙКИ</system:String>
О, кажется, Измените настройки лучше всего подходит

2024-09-18 10:35 UTC, torikki-tou commented on InvisibleMan-XRay/Assets/Localization/ru-RU.xaml
> +    <system:String x:Key="Lang.Message.NoSubscriptionRemarksEntered" xml:space="preserve">Название подписки не введено.&#10;Пожалуйста, заполните это поле.</system:String>
@smalyu давай оставим `название подписки`

@InvisibleManVPN we will call it subscription name in russian then. What about changing it in english too? `Remarks` seem like something unnecessary but subscription name is mandatory as far as i can see

2024-09-18 10:38 UTC, torikki-tou commented on InvisibleMan-XRay/Assets/Localization/ru-RU.xaml
> +    <system:String x:Key="Lang.Window.Settings.Tab.Log">Лог</system:String>
@smalyu `логи` понятны айтишникам и возможно геймерам по принципу близости к компьютерам, думаю обычному человеку, которого попросил скинуть логи приложения админ его сервера (для траблшутинга), будет понятнее слово журнал

2024-09-18 10:44 UTC, InvisibleManVPN commented on InvisibleMan-XRay/Assets/Localization/ru-RU.xaml
> +    <system:String x:Key="Lang.Message.NoSubscriptionRemarksEntered" xml:space="preserve">Название подписки не введено.&#10;Пожалуйста, заполните это поле.</system:String>
> @InvisibleManVPN we will call it subscription name in russian then. What about changing it in english too? `Remarks` seem like something unnecessary but subscription name is mandatory as far as i can see

@smalyu Good suggestion. We can do that, but in this PR just add the translation for Russian. In a particular PR, we can do that for English.

2024-09-18 13:29 UTC, torikki-tou commented on InvisibleMan-XRay/Assets/Localization/ru-RU.xaml
> +    <system:String x:Key="Lang.Window.Settings.Tab.Log">Лог</system:String>
We discassed it in DM and decided that current version is ok

2024-09-18 13:29 UTC, torikki-tou commented on InvisibleMan-XRay/Assets/Localization/ru-RU.xaml
> +    <system:String x:Key="Lang.Message.NoLogFile" xml:space="preserve">Файл лога для этой конфигурации отсутствует.&#10;Вы можете управлять логами через меню настроек.</system:String>
It is ok as mentioned in https://github.com/InvisibleManVPN/InvisibleMan-XRayClient/pull/129#discussion_r1765062654

2024-09-18 13:30 UTC, torikki-tou approved these changes

2024-09-19 06:39 UTC, InvisibleManVPN commented
Thank you @smalyu and @torikki-tou for your contribution!

2024-09-19 06:39 UTC, merged